In [2]:
from sklearn import datasets, model_selection
from sklearn.linear_model import LogisticRegression

d:\documents\codingninjas\venv\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [3]:
cancer_ds = datasets.load_breast_cancer()
x_train, x_test, y_train, y_test = model_selection.train_test_split(cancer_ds.data, cancer_ds.target)

print(x_train.shape)

(426, 30)


In [4]:
model = LogisticRegression()
model.fit(x_train, y_train)

d:\documents\codingninjas\venv\lib\site-packages\sklearn\linear_model\_logistic.py:939: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html.
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [5]:
model.score(x_test, y_test)

0.9370629370629371

In [6]:
model.predict_proba(x_train)[:10]

array([[4.72556339e-01, 5.27443661e-01],
       [1.84101047e-02, 9.81589895e-01],
       [1.00000000e+00, 1.21100907e-14],
       [8.17173745e-04, 9.99182826e-01],
       [7.51370169e-04, 9.99248630e-01],
       [1.53914020e-02, 9.84608598e-01],
       [5.29798741e-04, 9.99470201e-01],
       [1.76134775e-03, 9.98238652e-01],
       [5.22087089e-01, 4.77912911e-01],
       [1.00000000e+00, 1.78378431e-17]])

In [7]:
model.predict(x_train)-y_train

array([ 1,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0, -1,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0, -1,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  1,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,
        0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  1,  0,  1,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0

In [8]:
from sklearn.metrics import confusion_matrix

In [9]:
y_train_pred = model.predict(x_train)

confusion_matrix(y_train, y_train_pred)

array([[138,  13],
       [ 10, 265]], dtype=int64)