In [1]:
import numpy as np

In [2]:
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [0], [0], [1]])

x.shape, y.shape

((4, 2), (4, 1))

In [17]:
def derivative_sig(z):
    return sigmoid(z)*(1-sigmoid(z))

In [18]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [19]:
weights = 2 * np.random.random((2, 1)) - 1 # range bw -1 and 1
bias = 2 * np.random.random(1) - 1

weigths, bias

(array([[0.860711 ],
        [0.0665517]]), array([-0.55156303]))

In [20]:
output0 = x
output = sigmoid(np.dot(output0, weights) + bias)

output

array([[0.36550185],
       [0.55756954],
       [0.1966998 ],
       [0.34883073]])

In [21]:
wh = 2 * np.random.random((2, 2)) - 1
bh = 2 * np.random.random((1, 2)) - 1

wo = 2 * np.random.random((2, 1)) - 1
bo = 2 * np.random.random((1, 1)) - 1

In [22]:
output0 = x
outputHidden = sigmoid(np.dot(output0, wh) + bh)
output = sigmoid(np.dot(outputHidden, wo) + bo)

In [23]:
output

array([[0.58847752],
       [0.57285909],
       [0.55295489],
       [0.53635593]])